import { QuestionType, QuizSettings, DifficultyLevel, EducationStage, Semester } from './types';

export const EDUCATION_DATA = {
  [EducationStage.PRIMARY]: ['1', '2', '3', '4', '5', '6'],
  [EducationStage.PREPARATORY]: ['1', '2', '3'],
  [EducationStage.SECONDARY]: ['1', '2', '3']
};

export const SUBJECTS_LIST = ['لغة عربية', 'رياضيات', 'لغة انجليزية', 'علوم', 'دراسات', 'أخرى'];

export const MATH_BRANCHES = ['جبر', 'هندسة', 'حساب مثلثات', 'أخرى'];

export const UNIT_LABELS = ['وحدة', 'باب', 'فصل'];

export const DEFAULT_APPEARANCE = {
  backgroundColor: 'linear-gradient(135deg, #6a11cb, #2575fc)', 
  answerBoxBg: '#ffffff',
  answerTextColor: '#1e293b',
  selectedColor: '#9b59b6',
  selectedTextColor: '#ffffff',
  fontSizeChoices: 18,
  spacingChoices: 12,
  borderStyle: 'solid' as const,
  showSideColumn: true,
};

export const DEFAULT_SETTINGS: QuizSettings = {
  language: 'ar',
  title: 'كويز جديد',
  className: '',
  subject: 'لغة عربية',
  branch: '',
  unit: 'الأولى',
  lesson: '',
  timerEnabled: false,
  timerSeconds: 3600,
  teacherWhatsApp: '',
  skipNameEntry: false,
  welcomeMessage: 'مرحباً بك في الاختبار! بالتوفيق.',
  messageDuration: 5,
  maxAttempts: 0,
  appearance: DEFAULT_APPEARANCE,
  cloudConfig: {
    firebaseConfig: '',
    cloudUrl: '',
    folderName: '',
    syncGrades: true,
    syncTests: false,
    syncBank: false
  },
  schedulingEnabled: false,
  preventSplitScreen: false,
  preventScreenshot: false,
  offlineMode: false,
  designerName: '',
  designerLogo: '',
  copyrightPosition: 'center',
  defaultStage: EducationStage.PRIMARY,
  defaultGrade: '1',
  defaultSemester: Semester.FIRST,
};

export const CHOICE_COLORS = ['#e74c3c', '#3498db', '#2ecc71', '#f1c40f'];

export const TRANSLATIONS = {
  en: {
    dashboard: 'Teacher Dashboard',
    addQuestion: 'Add Question',
    questions: 'Questions',
    download: 'Download HTML',
    preview: 'Preview',
    share: 'Share',
    settings: 'Settings',
    builder: 'Editor',
    cloud: 'Cloud',
    bank: 'Bank',
    library: 'Library',
    warning: 'Warning: No questions added!',
    title: 'Quiz Title',
    className: 'Class Name',
    subject: 'Subject',
    branch: 'Branch',
    unit: 'Unit',
    unitLabel: 'Unit Type',
    lesson: 'Lesson',
    whatsapp: 'Teacher WhatsApp',
    timer: 'Exam Duration',
    timerMinutes: 'Minutes',
    timerSeconds: 'Seconds',
    skipName: 'Skip Name Entry',
    guestDesc: 'Allows entry without typing name',
    welcome: 'Welcome Screen',
    autoClose: 'Auto-close (sec)',
    appearance: 'Appearance',
    testBg: 'Test Background',
    sidebar: 'Sidebar Column',
    answerText: 'Answer Text Color',
    selectionBg: 'Selected Choice Color',
    fontSize: 'Font Size',
    spacing: 'Option Spacing',
    border: 'Border Style',
    general: 'General Configuration',
    category: 'Bank Category',
    type: 'Type',
    difficulty: 'Difficulty',
    points: 'Points',
    image: 'Image Attachment',
    upload: 'Upload from device',
    answers: 'Answers',
    bgOverride: 'Background Override',
    finish: 'Finish Test',
    score: 'Score',
    results: 'Results',
    sendWhatsApp: 'Send to Teacher',
    tryAgain: 'Try Again',
    prev: 'Previous',
    next: 'Next',
    summaryTitle: 'Complete Your Test',
    summaryDesc: 'Make sure you have answered all questions.',
    finalSub: 'Final Submission',
    back: 'Back to Questions',
    unanswered: 'You have unanswered questions:',
    allAnswered: 'Great job! All questions have been answered.',
    lang: 'Language',
    enterName: 'Please enter your name:',
    studentName: 'Student Name',
    enterTest: 'Enter Test',
    time: 'Time',
    optional: 'Optional',
    exit: 'Exit',
    exitTip: 'You can now close this tab safely',
    matchingLeft: 'Item',
    matchingRight: 'Match',
    correctAnswerLabel: 'Correct Answer',
    branding: 'Copyright & Branding',
    designer: 'Designer Name',
    logo: 'Logo',
    position: 'Position',
    posLeft: 'Left',
    posCenter: 'Center',
    posRight: 'Right',
    maxAttemptsLabel: 'Attempts Limit',
    unlimitedAttempts: 'Unlimited',
    singleAttempt: 'One Attempt Only',
    attemptsReached: 'Maximum attempts reached.',
    security: 'Security & Proctoring',
    noSplitScreen: 'Prevent Split Screen / Focus Loss',
    noScreenshot: 'Prevent Screenshot (Partial)',
    offlineOnly: 'Work Offline Mode',
    securityWarning: 'Security Warning',
    focusLostMsg: 'Please do not leave the test screen. Your focus was lost.',
    offlineWarning: 'This test is configured for offline use only. Please disconnect from internet.',
    scheduling: 'Exam Scheduling',
    schedulingEnabled: 'Enable Availability Time',
    startTime: 'Start Time',
    endTime: 'End Time',
    notYetAvailable: 'Test is not available yet.',
    expired: 'Test has expired.',
    cloudTitle: 'Cloud Sync Configuration',
    firebaseLabel: 'Firebase Config (JSON/URL)',
    cloudUrlLabel: 'Cloud Server URL',
    folderNameLabel: 'Cloud Folder Name',
    syncOptions: 'Storage Options',
    syncGradesLabel: 'Sync Student Grades',
    syncTestsLabel: 'Save Tests in Cloud',
    syncBankLabel: 'Question Bank Sync',
    yes: 'Yes',
    cancel: 'Cancel',
    confirmFinish: 'Confirm Finish',
    confirmFinishMsg: 'Are you sure you want to finish the test?',
    confirmExit: 'Confirm Exit',
    confirmExitMsg: 'Are you sure you want to exit the quiz?',
    unansweredAlert: "Warning: You haven't answered all questions. Do you want to continue?",
    stages: {
      [EducationStage.PRIMARY]: 'Primary',
      [EducationStage.PREPARATORY]: 'Preparatory',
      [EducationStage.SECONDARY]: 'Secondary',
    },
    semesters: {
      [Semester.FIRST]: '1st Semester',
      [Semester.SECOND]: '2nd Semester',
    },
    stage: 'Stage',
    grade: 'Grade',
    semester: 'Semester',
    search: 'Search questions...',
    import: 'Import',
    export: 'Export to Bank',
    saveToLibrary: 'Save to Library',
    load: 'Load Quiz',
    emptyBank: 'Bank is empty. Export questions from the editor!',
    emptyLibrary: 'Library is empty. Save your quizzes!',
    other: 'Other',
    addOther: 'Add custom...',
    unitLabels: {
      'وحدة': 'Unit',
      'باب': 'Chapter',
      'فصل': 'Section'
    },
    feedback: {
      excellent: 'Excellent! You are a genius! 🌟',
      veryGood: 'Very Good! Keep up the great work! 👏',
      good: 'Good job! You can do even better! 👍',
      fair: "Not bad! A little more study and you'll succeed! 📖",
      poor: "Hard luck! Don't give up, try again! 💪"
    },
    difficultyLevels: {
      [DifficultyLevel.HIGH]: 'High',
      [DifficultyLevel.MEDIUM]: 'Medium',
      [DifficultyLevel.EASY]: 'Easy'
    },
    questionTypes: {
      [QuestionType.MULTIPLE_CHOICE]: 'Multiple Choice',
      [QuestionType.TRUE_FALSE]: 'True/False',
      [QuestionType.FILL_IN_THE_BLANK]: 'Fill in the blank',
      [QuestionType.ESSAY]: 'Essay',
      [QuestionType.MATCHING]: 'Matching',
      [QuestionType.OTHER]: 'Other'
    }
  },
  ar: {
    dashboard: 'لوحة تحكم المعلم',
    addQuestion: 'إضافة سؤال',
    questions: 'الأسئلة',
    download: 'تحميل الاختبار',
    preview: 'معاينة',
    share: 'مشاركة',
    settings: 'الإعدادات',
    builder: 'منشئ الاختبار',
    cloud: 'السحابة',
    bank: 'بنك الأسئلة',
    library: 'المكتبة',
    warning: 'تنبيه: لا توجد أسئلة!',
    title: 'عنوان الاختبار',
    className: 'اسم الصف',
    subject: 'المادة',
    branch: 'الفرع',
    unit: 'اسم الوحدة/الباب',
    unitLabel: 'التصنيف',
    lesson: 'اسم الدرس',
    whatsapp: 'واتساب المعلم',
    timer: 'زمن الاختبار (المدة)',
    timerMinutes: 'دقيقة',
    timerSeconds: 'ثانية',
    skipName: 'تجاوز إدخال الاسم',
    guestDesc: 'يسمح بالدخول دون كتابة الاسم',
    welcome: 'شاشة الترحيب',
    autoClose: 'إغلاق تلقائي (ثواني)',
    appearance: 'المظهر',
    testBg: 'خلفية الاختبار',
    sidebar: 'عمود جانبي مرقم',
    answerText: 'لون نص الإجابة',
    selectionBg: 'لون الخيار المحدد',
    fontSize: 'حجم الخط',
    spacing: 'المسافة بين الخيارات',
    border: 'شكل الحدود',
    general: 'الإعدادات الأساسية',
    category: 'تصنيف بنك الأسئلة',
    type: 'نوع السؤال',
    difficulty: 'مستوى الصعوبة',
    points: 'النقاط',
    image: 'إرفاق صورة',
    upload: 'رفع من الجهاز',
    answers: 'الإجابات',
    bgOverride: 'تغيير خلفية السؤال',
    finish: 'إنهاء الاختبار',
    score: 'الدرجة',
    results: 'نتائج الاختبار',
    sendWhatsApp: 'إرسال للمعلم',
    tryAgain: 'إعادة المحاولة',
    prev: 'السابق',
    next: 'التالي',
    summaryTitle: 'إكمال الاختبار',
    summaryDesc: 'تأكد من إجابتك على جميع الأسئلة.',
    finalSub: 'تسليم نهائي',
    back: 'العودة للأسئلة',
    unanswered: 'لديك أسئلة غير مجابة:',
    allAnswered: 'عمل رائع! لقد أجبت على جميع الأسئلة.',
    lang: 'اللغة',
    enterName: 'يرجى إدخال اسمك:',
    studentName: 'اسم الطالب',
    enterTest: 'دخول الاختبار',
    time: 'الوقت',
    optional: 'اختياري',
    exit: 'خروج',
    exitTip: 'يمكنك إغلاق هذه الصفحة الآن بأمان.',
    matchingLeft: 'العنصر',
    matchingRight: 'المقابل',
    correctAnswerLabel: 'الإجابة الصحيحة',
    branding: 'حقوق الملكية والمصمم',
    designer: 'اسم المصمم',
    logo: 'اللوجو',
    position: 'مكان الظهور',
    posLeft: 'يسار',
    posCenter: 'وسط',
    posRight: 'يمين',
    maxAttemptsLabel: 'عدد المحاولات',
    unlimitedAttempts: 'غير محدود',
    singleAttempt: 'محاولة واحدة فقط',
    attemptsReached: 'استنفدت المحاولات.',
    security: 'إعدادات الأمان والمراقبة',
    noSplitScreen: 'منع تقسيم الشاشة / حماية التركيز',
    noScreenshot: 'منع لقطة الشاشة (محاولة)',
    offlineOnly: 'وضع عدم استخدام الإنترنت (أوفلاين)',
    securityWarning: 'تنبيه أمني',
    focusLostMsg: 'يرجى عدم مغادرة صفحة الاختبار أو تقسيم الشاشة لضمان نزاهة الحل.',
    offlineWarning: 'هذا الاختبار مخصص للحل بدون إنترنت. يرجى فصل الاتصال للمتابعة.',
    scheduling: 'جدولة موعد الاختبار',
    schedulingEnabled: 'تفعيل وقت متاح للاختبار',
    startTime: 'وقت البداية',
    endTime: 'وقت النهاية',
    notYetAvailable: 'عذراً، الاختبار غير متاح حالياً. يرجى العودة في الموعد المحدد.',
    expired: 'عذراً، انتهى الوقت المخصص لدخول الاختبار.',
    cloudTitle: 'إعدادات المزامنة السحابية',
    firebaseLabel: 'ملف الفايربيس (JSON/URL)',
    cloudUrlLabel: 'عنوان المخزن السحابي (API)',
    folderNameLabel: 'اسم المجلد في السحابة',
    syncOptions: 'خيارات التخزين والمزامنة',
    syncGradesLabel: 'تخزين درجات الطلاب تلقائياً',
    syncTestsLabel: 'حفظ الاختبارات في السحابة',
    syncBankLabel: 'مزامنة بنك الأسئلة',
    yes: 'نعم',
    cancel: 'إلغاء',
    confirmFinish: 'تأكيد الإنهاء',
    confirmFinishMsg: 'هل أنت متأكد من إنهاء الاختبار؟',
    confirmExit: 'تأكيد الخروج',
    confirmExitMsg: 'هل أنت متأكد من رغبتك في الخروج من الاختبار؟',
    unansweredAlert: 'تنبيه: لم تجب على جميع الأسئلة. هل تريد المتابعة والإنهاء؟',
    stages: {
      [EducationStage.PRIMARY]: 'الابتدائية',
      [EducationStage.PREPARATORY]: 'الإعدادية',
      [EducationStage.SECONDARY]: 'الثانوية',
    },
    semesters: {
      [Semester.FIRST]: 'الفصل الدراسي الأول',
      [Semester.SECOND]: 'الفصل الدراسي الثاني',
    },
    stage: 'المرحلة',
    grade: 'الصف',
    semester: 'الفصل الدراسي',
    search: 'ابحث في الأسئلة...',
    import: 'استيراد',
    export: 'تصدير للبنك',
    saveToLibrary: 'حفظ في المكتبة',
    load: 'فتح الاختبار',
    emptyBank: 'بنك الأسئلة فارغ. قم بتصدير أسئلة من المحرر!',
    emptyLibrary: 'المكتبة فارغة. احفظ اختباراتك لتظهر هنا!',
    other: 'أخرى',
    addOther: 'إضافة مخصص...',
    unitLabels: {
      'وحدة': 'وحدة',
      'باب': 'باب',
      'فصل': 'فصل'
    },
    feedback: {
      excellent: 'ممتاز! أنت عبقري ومتميز! 🌟',
      veryGood: 'أحسنت صنعاً! عمل رائع ومستمر! 👏',
      good: 'جيد جداً! بإمكانك تحقيق الأفضل دائماً! 👍',
      fair: 'لا بأس! القليل من المذاكرة وستتفوّق! 📖',
      poor: 'حظاً أوفر! لا تستسلم، حاول مرة أخرى! 💪'
    },
    difficultyLevels: {
      [DifficultyLevel.HIGH]: 'عليا',
      [DifficultyLevel.MEDIUM]: 'متوسط',
      [DifficultyLevel.EASY]: 'سهل'
    },
    questionTypes: {
      [QuestionType.MULTIPLE_CHOICE]: 'اختيارات',
      [QuestionType.TRUE_FALSE]: 'صح / خطأ',
      [QuestionType.FILL_IN_THE_BLANK]: 'أكمل',
      [QuestionType.ESSAY]: 'مقالي',
      [QuestionType.MATCHING]: 'توصيل',
      [QuestionType.OTHER]: 'أخرى'
    }
  }
};
